### ISSUE TITLE
外部依赖问题

### ISSUE THREAD

**Issue by chuangwang1991** [huyaoyu/ImageMatching#1]
胡师兄，这个run,py里面应该有你们自己开发的一些依赖吧，在‘run.py’ line 11, 'from CommonPython.Filesystem import Filesystem', 还有 line 239 ‘from input_conf import conf’，CommonPython的包我找到了，但是这个‘input_conf’的没找到  - -..

**Comment by huyaoyu** [comment]
input_conf实际上是一个python文件形式的输入文件。使用run.py脚本时，需要指定一个working directory。在这个working directory下需要有一个`input_conf.py`文件。下面是一个使用OpenCV作为后端的实例
```python
conf = dict(
    proxy=dict(
        type='ProxyFeatExtOCV',
        longer_edge=1024,
        feature_type='surf',
        hessian=200,
    )
)
```
类似地，使用SuperGlue时
```python
conf = dict(
    proxy=dict(
        type='ProxySuperGlue',
        superglue='outdoor',
        keypoint_threshold=0.005,
        max_keypoints=-1,
        nms_radius=4,
        sinkhorn_iterations=20,
        match_threshold=0.2,
        longer_edge=1024,
    )
)
```
